/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2RouteImport } from './routes/2'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AssetIntelligenceHubRouteImport } from './routes/asset-intelligence-hub'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookADemoRouteImport } from './routes/book-a-demo'
import { Route as CustomerStoriesRouteImport } from './routes/customer-stories'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HelpCentreRouteImport } from './routes/help-centre'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PortfolioIntelligenceRouteImport } from './routes/portfolio-intelligence'
import { Route as RequestADemoRouteImport } from './routes/request-a-demo'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSetPasswordRouteImport } from './routes/admin/set-password'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CompanyAboutRouteImport } from './routes/company/about'
import { Route as CompanyCareersRouteImport } from './routes/company/careers'
import { Route as CompanyContactRouteImport } from './routes/company/contact'
import { Route as CompanyPartnersRouteImport } from './routes/company/partners'
import { Route as CustomerStoriesIndexRouteImport } from './routes/customer-stories.index'
import { Route as CustomerStoriesSlugRouteImport } from './routes/customer-stories.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as HelpCentreIndexRouteImport } from './routes/help-centre.index'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalServiceLevelTermsRouteImport } from './routes/legal/service-level-terms'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as SolutionsAcquisitionsDueDiligenceRouteImport } from './routes/solutions/acquisitions-due-diligence'
import { Route as SolutionsAssetManagersRouteImport } from './routes/solutions/asset-managers'
import { Route as SolutionsBuildingSurveyorsRouteImport } from './routes/solutions/building-surveyors'
import { Route as SolutionsInvestmentManagersRouteImport } from './routes/solutions/investment-managers'
import { Route as SolutionsLegalsRouteImport } from './routes/solutions/legals'
import { Route as SolutionsPropertyManagersRouteImport } from './routes/solutions/property-managers'
import { Route as UseCasesAssetDocumentReviewRouteImport } from './routes/use-cases/asset-document-review'
import { Route as UseCasesCriticalDatesRouteImport } from './routes/use-cases/critical-dates'
import { Route as UseCasesDilapidationsRouteImport } from './routes/use-cases/dilapidations'
import { Route as UseCasesDueDiligenceRouteImport } from './routes/use-cases/due-diligence'
import { Route as UseCasesLeaseIntelligenceRouteImport } from './routes/use-cases/lease-intelligence'
import { Route as UseCasesRightsAndObligationsRouteImport } from './routes/use-cases/rights-and-obligations'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminHelpIndexRouteImport } from './routes/admin/help/index'
import { Route as AdminHelpIdRouteImport } from './routes/admin/help/$id'
import { Route as AdminHelpNewRouteImport } from './routes/admin/help/new'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin/resources/index'
import { Route as AdminResourcesIdRouteImport } from './routes/admin/resources/$id'
import { Route as AdminResourcesNewRouteImport } from './routes/admin/resources/new'
import { Route as AdminSettingsFormsRouteImport } from './routes/admin/settings/forms'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin/settings/general'
import { Route as AdminSettingsIntegrationsRouteImport } from './routes/admin/settings/integrations'
import { Route as AdminSettingsSeoRouteImport } from './routes/admin/settings/seo'
import { Route as AdminSettingsTeamRouteImport } from './routes/admin/settings/team'
import { Route as AdminStoriesIndexRouteImport } from './routes/admin/stories/index'
import { Route as AdminStoriesIdRouteImport } from './routes/admin/stories/$id'
import { Route as AdminStoriesNewRouteImport } from './routes/admin/stories/new'
import { Route as HelpCentreCategorySlugRouteImport } from './routes/help-centre.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIntelligenceHubRoute = AssetIntelligenceHubRouteImport.update({
  id: '/asset-intelligence-hub',
  path: '/asset-intelligence-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookADemoRoute = BookADemoRouteImport.update({
  id: '/book-a-demo',
  path: '/book-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerStoriesRoute = CustomerStoriesRouteImport.update({
  id: '/customer-stories',
  path: '/customer-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCentreRoute = HelpCentreRouteImport.update({
  id: '/help-centre',
  path: '/help-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIntelligenceRoute = PortfolioIntelligenceRouteImport.update({
  id: '/portfolio-intelligence',
  path: '/portfolio-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestADemoRoute = RequestADemoRouteImport.update({
  id: '/request-a-demo',
  path: '/request-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCareersRoute = CompanyCareersRouteImport.update({
  id: '/company/careers',
  path: '/company/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/company/contact',
  path: '/company/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPartnersRoute = CompanyPartnersRouteImport.update({
  id: '/company/partners',
  path: '/company/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerStoriesIndexRoute = CustomerStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerStoriesRoute,
} as any)
const CustomerStoriesSlugRoute = CustomerStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CustomerStoriesRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const HelpCentreIndexRoute = HelpCentreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpCentreRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalServiceLevelTermsRoute = LegalServiceLevelTermsRouteImport.update({
  id: '/legal/service-level-terms',
  path: '/legal/service-level-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAcquisitionsDueDiligenceRoute =
  SolutionsAcquisitionsDueDiligenceRouteImport.update({
    id: '/solutions/acquisitions-due-diligence',
    path: '/solutions/acquisitions-due-diligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAssetManagersRoute = SolutionsAssetManagersRouteImport.update({
  id: '/solutions/asset-managers',
  path: '/solutions/asset-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBuildingSurveyorsRoute =
  SolutionsBuildingSurveyorsRouteImport.update({
    id: '/solutions/building-surveyors',
    path: '/solutions/building-surveyors',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsInvestmentManagersRoute =
  SolutionsInvestmentManagersRouteImport.update({
    id: '/solutions/investment-managers',
    path: '/solutions/investment-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsLegalsRoute = SolutionsLegalsRouteImport.update({
  id: '/solutions/legals',
  path: '/solutions/legals',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPropertyManagersRoute =
  SolutionsPropertyManagersRouteImport.update({
    id: '/solutions/property-managers',
    path: '/solutions/property-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesAssetDocumentReviewRoute =
  UseCasesAssetDocumentReviewRouteImport.update({
    id: '/use-cases/asset-document-review',
    path: '/use-cases/asset-document-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesCriticalDatesRoute = UseCasesCriticalDatesRouteImport.update({
  id: '/use-cases/critical-dates',
  path: '/use-cases/critical-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesDilapidationsRoute = UseCasesDilapidationsRouteImport.update({
  id: '/use-cases/dilapidations',
  path: '/use-cases/dilapidations',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesDueDiligenceRoute = UseCasesDueDiligenceRouteImport.update({
  id: '/use-cases/due-diligence',
  path: '/use-cases/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesLeaseIntelligenceRoute =
  UseCasesLeaseIntelligenceRouteImport.update({
    id: '/use-cases/lease-intelligence',
    path: '/use-cases/lease-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesRightsAndObligationsRoute =
  UseCasesRightsAndObligationsRouteImport.update({
    id: '/use-cases/rights-and-obligations',
    path: '/use-cases/rights-and-obligations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpIndexRoute = AdminHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpIdRoute = AdminHelpIdRouteImport.update({
  id: '/help/$id',
  path: '/help/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpNewRoute = AdminHelpNewRouteImport.update({
  id: '/help/new',
  path: '/help/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesNewRoute = AdminResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsFormsRoute = AdminSettingsFormsRouteImport.update({
  id: '/settings/forms',
  path: '/settings/forms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIntegrationsRoute =
  AdminSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSettingsSeoRoute = AdminSettingsSeoRouteImport.update({
  id: '/settings/seo',
  path: '/settings/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsTeamRoute = AdminSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoriesIndexRoute = AdminStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoriesIdRoute = AdminStoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoriesNewRoute = AdminStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HelpCentreCategorySlugRoute = HelpCentreCategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => HelpCentreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/2': typeof R2Route
  '/asset-intelligence-hub': typeof AssetIntelligenceHubRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-demo': typeof BookADemoRoute
  '/customer-stories': typeof CustomerStoriesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/help-centre': typeof HelpCentreRouteWithChildren
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/security': typeof SecurityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customer-stories/$slug': typeof CustomerStoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/service-level-terms': typeof LegalServiceLevelTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/solutions/acquisitions-due-diligence': typeof SolutionsAcquisitionsDueDiligenceRoute
  '/solutions/asset-managers': typeof SolutionsAssetManagersRoute
  '/solutions/building-surveyors': typeof SolutionsBuildingSurveyorsRoute
  '/solutions/investment-managers': typeof SolutionsInvestmentManagersRoute
  '/solutions/legals': typeof SolutionsLegalsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/use-cases/asset-document-review': typeof UseCasesAssetDocumentReviewRoute
  '/use-cases/critical-dates': typeof UseCasesCriticalDatesRoute
  '/use-cases/dilapidations': typeof UseCasesDilapidationsRoute
  '/use-cases/due-diligence': typeof UseCasesDueDiligenceRoute
  '/use-cases/lease-intelligence': typeof UseCasesLeaseIntelligenceRoute
  '/use-cases/rights-and-obligations': typeof UseCasesRightsAndObligationsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/customer-stories/': typeof CustomerStoriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/help-centre/': typeof HelpCentreIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/help/$id': typeof AdminHelpIdRoute
  '/admin/help/new': typeof AdminHelpNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/stories/$id': typeof AdminStoriesIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/help-centre/$category/$slug': typeof HelpCentreCategorySlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/help/': typeof AdminHelpIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/stories/': typeof AdminStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2': typeof R2Route
  '/asset-intelligence-hub': typeof AssetIntelligenceHubRoute
  '/book-a-demo': typeof BookADemoRoute
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/security': typeof SecurityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customer-stories/$slug': typeof CustomerStoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/service-level-terms': typeof LegalServiceLevelTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/solutions/acquisitions-due-diligence': typeof SolutionsAcquisitionsDueDiligenceRoute
  '/solutions/asset-managers': typeof SolutionsAssetManagersRoute
  '/solutions/building-surveyors': typeof SolutionsBuildingSurveyorsRoute
  '/solutions/investment-managers': typeof SolutionsInvestmentManagersRoute
  '/solutions/legals': typeof SolutionsLegalsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/use-cases/asset-document-review': typeof UseCasesAssetDocumentReviewRoute
  '/use-cases/critical-dates': typeof UseCasesCriticalDatesRoute
  '/use-cases/dilapidations': typeof UseCasesDilapidationsRoute
  '/use-cases/due-diligence': typeof UseCasesDueDiligenceRoute
  '/use-cases/lease-intelligence': typeof UseCasesLeaseIntelligenceRoute
  '/use-cases/rights-and-obligations': typeof UseCasesRightsAndObligationsRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/customer-stories': typeof CustomerStoriesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/help-centre': typeof HelpCentreIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/help/$id': typeof AdminHelpIdRoute
  '/admin/help/new': typeof AdminHelpNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/stories/$id': typeof AdminStoriesIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/help-centre/$category/$slug': typeof HelpCentreCategorySlugRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/help': typeof AdminHelpIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/stories': typeof AdminStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/2': typeof R2Route
  '/asset-intelligence-hub': typeof AssetIntelligenceHubRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-demo': typeof BookADemoRoute
  '/customer-stories': typeof CustomerStoriesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/help-centre': typeof HelpCentreRouteWithChildren
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/security': typeof SecurityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customer-stories/$slug': typeof CustomerStoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/service-level-terms': typeof LegalServiceLevelTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/solutions/acquisitions-due-diligence': typeof SolutionsAcquisitionsDueDiligenceRoute
  '/solutions/asset-managers': typeof SolutionsAssetManagersRoute
  '/solutions/building-surveyors': typeof SolutionsBuildingSurveyorsRoute
  '/solutions/investment-managers': typeof SolutionsInvestmentManagersRoute
  '/solutions/legals': typeof SolutionsLegalsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/use-cases/asset-document-review': typeof UseCasesAssetDocumentReviewRoute
  '/use-cases/critical-dates': typeof UseCasesCriticalDatesRoute
  '/use-cases/dilapidations': typeof UseCasesDilapidationsRoute
  '/use-cases/due-diligence': typeof UseCasesDueDiligenceRoute
  '/use-cases/lease-intelligence': typeof UseCasesLeaseIntelligenceRoute
  '/use-cases/rights-and-obligations': typeof UseCasesRightsAndObligationsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/customer-stories/': typeof CustomerStoriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/help-centre/': typeof HelpCentreIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/help/$id': typeof AdminHelpIdRoute
  '/admin/help/new': typeof AdminHelpNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/stories/$id': typeof AdminStoriesIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/help-centre/$category/$slug': typeof HelpCentreCategorySlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/help/': typeof AdminHelpIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/stories/': typeof AdminStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/2'
    | '/asset-intelligence-hub'
    | '/blog'
    | '/book-a-demo'
    | '/customer-stories'
    | '/guides'
    | '/help-centre'
    | '/platform'
    | '/portfolio-intelligence'
    | '/request-a-demo'
    | '/security'
    | '/admin/login'
    | '/admin/set-password'
    | '/admin/submissions'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/partners'
    | '/customer-stories/$slug'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/service-level-terms'
    | '/legal/terms'
    | '/solutions/acquisitions-due-diligence'
    | '/solutions/asset-managers'
    | '/solutions/building-surveyors'
    | '/solutions/investment-managers'
    | '/solutions/legals'
    | '/solutions/property-managers'
    | '/use-cases/asset-document-review'
    | '/use-cases/critical-dates'
    | '/use-cases/dilapidations'
    | '/use-cases/due-diligence'
    | '/use-cases/lease-intelligence'
    | '/use-cases/rights-and-obligations'
    | '/admin/'
    | '/blog/'
    | '/customer-stories/'
    | '/guides/'
    | '/help-centre/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/help/$id'
    | '/admin/help/new'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/admin/settings/forms'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/seo'
    | '/admin/settings/team'
    | '/admin/stories/$id'
    | '/admin/stories/new'
    | '/help-centre/$category/$slug'
    | '/admin/blog/'
    | '/admin/help/'
    | '/admin/resources/'
    | '/admin/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2'
    | '/asset-intelligence-hub'
    | '/book-a-demo'
    | '/platform'
    | '/portfolio-intelligence'
    | '/request-a-demo'
    | '/security'
    | '/admin/login'
    | '/admin/set-password'
    | '/admin/submissions'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/partners'
    | '/customer-stories/$slug'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/service-level-terms'
    | '/legal/terms'
    | '/solutions/acquisitions-due-diligence'
    | '/solutions/asset-managers'
    | '/solutions/building-surveyors'
    | '/solutions/investment-managers'
    | '/solutions/legals'
    | '/solutions/property-managers'
    | '/use-cases/asset-document-review'
    | '/use-cases/critical-dates'
    | '/use-cases/dilapidations'
    | '/use-cases/due-diligence'
    | '/use-cases/lease-intelligence'
    | '/use-cases/rights-and-obligations'
    | '/admin'
    | '/blog'
    | '/customer-stories'
    | '/guides'
    | '/help-centre'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/help/$id'
    | '/admin/help/new'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/admin/settings/forms'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/seo'
    | '/admin/settings/team'
    | '/admin/stories/$id'
    | '/admin/stories/new'
    | '/help-centre/$category/$slug'
    | '/admin/blog'
    | '/admin/help'
    | '/admin/resources'
    | '/admin/stories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/2'
    | '/asset-intelligence-hub'
    | '/blog'
    | '/book-a-demo'
    | '/customer-stories'
    | '/guides'
    | '/help-centre'
    | '/platform'
    | '/portfolio-intelligence'
    | '/request-a-demo'
    | '/security'
    | '/admin/login'
    | '/admin/set-password'
    | '/admin/submissions'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/partners'
    | '/customer-stories/$slug'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/service-level-terms'
    | '/legal/terms'
    | '/solutions/acquisitions-due-diligence'
    | '/solutions/asset-managers'
    | '/solutions/building-surveyors'
    | '/solutions/investment-managers'
    | '/solutions/legals'
    | '/solutions/property-managers'
    | '/use-cases/asset-document-review'
    | '/use-cases/critical-dates'
    | '/use-cases/dilapidations'
    | '/use-cases/due-diligence'
    | '/use-cases/lease-intelligence'
    | '/use-cases/rights-and-obligations'
    | '/admin/'
    | '/blog/'
    | '/customer-stories/'
    | '/guides/'
    | '/help-centre/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/help/$id'
    | '/admin/help/new'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/admin/settings/forms'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/seo'
    | '/admin/settings/team'
    | '/admin/stories/$id'
    | '/admin/stories/new'
    | '/help-centre/$category/$slug'
    | '/admin/blog/'
    | '/admin/help/'
    | '/admin/resources/'
    | '/admin/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  R2Route: typeof R2Route
  AssetIntelligenceHubRoute: typeof AssetIntelligenceHubRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookADemoRoute: typeof BookADemoRoute
  CustomerStoriesRoute: typeof CustomerStoriesRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  HelpCentreRoute: typeof HelpCentreRouteWithChildren
  PlatformRoute: typeof PlatformRoute
  PortfolioIntelligenceRoute: typeof PortfolioIntelligenceRoute
  RequestADemoRoute: typeof RequestADemoRoute
  SecurityRoute: typeof SecurityRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyCareersRoute: typeof CompanyCareersRoute
  CompanyContactRoute: typeof CompanyContactRoute
  CompanyPartnersRoute: typeof CompanyPartnersRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalServiceLevelTermsRoute: typeof LegalServiceLevelTermsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SolutionsAcquisitionsDueDiligenceRoute: typeof SolutionsAcquisitionsDueDiligenceRoute
  SolutionsAssetManagersRoute: typeof SolutionsAssetManagersRoute
  SolutionsBuildingSurveyorsRoute: typeof SolutionsBuildingSurveyorsRoute
  SolutionsInvestmentManagersRoute: typeof SolutionsInvestmentManagersRoute
  SolutionsLegalsRoute: typeof SolutionsLegalsRoute
  SolutionsPropertyManagersRoute: typeof SolutionsPropertyManagersRoute
  UseCasesAssetDocumentReviewRoute: typeof UseCasesAssetDocumentReviewRoute
  UseCasesCriticalDatesRoute: typeof UseCasesCriticalDatesRoute
  UseCasesDilapidationsRoute: typeof UseCasesDilapidationsRoute
  UseCasesDueDiligenceRoute: typeof UseCasesDueDiligenceRoute
  UseCasesLeaseIntelligenceRoute: typeof UseCasesLeaseIntelligenceRoute
  UseCasesRightsAndObligationsRoute: typeof UseCasesRightsAndObligationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2': {
      id: '/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-intelligence-hub': {
      id: '/asset-intelligence-hub'
      path: '/asset-intelligence-hub'
      fullPath: '/asset-intelligence-hub'
      preLoaderRoute: typeof AssetIntelligenceHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-demo': {
      id: '/book-a-demo'
      path: '/book-a-demo'
      fullPath: '/book-a-demo'
      preLoaderRoute: typeof BookADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-stories': {
      id: '/customer-stories'
      path: '/customer-stories'
      fullPath: '/customer-stories'
      preLoaderRoute: typeof CustomerStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-centre': {
      id: '/help-centre'
      path: '/help-centre'
      fullPath: '/help-centre'
      preLoaderRoute: typeof HelpCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-intelligence': {
      id: '/portfolio-intelligence'
      path: '/portfolio-intelligence'
      fullPath: '/portfolio-intelligence'
      preLoaderRoute: typeof PortfolioIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-demo': {
      id: '/request-a-demo'
      path: '/request-a-demo'
      fullPath: '/request-a-demo'
      preLoaderRoute: typeof RequestADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/careers': {
      id: '/company/careers'
      path: '/company/careers'
      fullPath: '/company/careers'
      preLoaderRoute: typeof CompanyCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/contact': {
      id: '/company/contact'
      path: '/company/contact'
      fullPath: '/company/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/partners': {
      id: '/company/partners'
      path: '/company/partners'
      fullPath: '/company/partners'
      preLoaderRoute: typeof CompanyPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-stories/': {
      id: '/customer-stories/'
      path: '/'
      fullPath: '/customer-stories/'
      preLoaderRoute: typeof CustomerStoriesIndexRouteImport
      parentRoute: typeof CustomerStoriesRoute
    }
    '/customer-stories/$slug': {
      id: '/customer-stories/$slug'
      path: '/$slug'
      fullPath: '/customer-stories/$slug'
      preLoaderRoute: typeof CustomerStoriesSlugRouteImport
      parentRoute: typeof CustomerStoriesRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/help-centre/': {
      id: '/help-centre/'
      path: '/'
      fullPath: '/help-centre/'
      preLoaderRoute: typeof HelpCentreIndexRouteImport
      parentRoute: typeof HelpCentreRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/service-level-terms': {
      id: '/legal/service-level-terms'
      path: '/legal/service-level-terms'
      fullPath: '/legal/service-level-terms'
      preLoaderRoute: typeof LegalServiceLevelTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/acquisitions-due-diligence': {
      id: '/solutions/acquisitions-due-diligence'
      path: '/solutions/acquisitions-due-diligence'
      fullPath: '/solutions/acquisitions-due-diligence'
      preLoaderRoute: typeof SolutionsAcquisitionsDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/asset-managers': {
      id: '/solutions/asset-managers'
      path: '/solutions/asset-managers'
      fullPath: '/solutions/asset-managers'
      preLoaderRoute: typeof SolutionsAssetManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/building-surveyors': {
      id: '/solutions/building-surveyors'
      path: '/solutions/building-surveyors'
      fullPath: '/solutions/building-surveyors'
      preLoaderRoute: typeof SolutionsBuildingSurveyorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/investment-managers': {
      id: '/solutions/investment-managers'
      path: '/solutions/investment-managers'
      fullPath: '/solutions/investment-managers'
      preLoaderRoute: typeof SolutionsInvestmentManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/legals': {
      id: '/solutions/legals'
      path: '/solutions/legals'
      fullPath: '/solutions/legals'
      preLoaderRoute: typeof SolutionsLegalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/property-managers': {
      id: '/solutions/property-managers'
      path: '/solutions/property-managers'
      fullPath: '/solutions/property-managers'
      preLoaderRoute: typeof SolutionsPropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/asset-document-review': {
      id: '/use-cases/asset-document-review'
      path: '/use-cases/asset-document-review'
      fullPath: '/use-cases/asset-document-review'
      preLoaderRoute: typeof UseCasesAssetDocumentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/critical-dates': {
      id: '/use-cases/critical-dates'
      path: '/use-cases/critical-dates'
      fullPath: '/use-cases/critical-dates'
      preLoaderRoute: typeof UseCasesCriticalDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/dilapidations': {
      id: '/use-cases/dilapidations'
      path: '/use-cases/dilapidations'
      fullPath: '/use-cases/dilapidations'
      preLoaderRoute: typeof UseCasesDilapidationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/due-diligence': {
      id: '/use-cases/due-diligence'
      path: '/use-cases/due-diligence'
      fullPath: '/use-cases/due-diligence'
      preLoaderRoute: typeof UseCasesDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/lease-intelligence': {
      id: '/use-cases/lease-intelligence'
      path: '/use-cases/lease-intelligence'
      fullPath: '/use-cases/lease-intelligence'
      preLoaderRoute: typeof UseCasesLeaseIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/rights-and-obligations': {
      id: '/use-cases/rights-and-obligations'
      path: '/use-cases/rights-and-obligations'
      fullPath: '/use-cases/rights-and-obligations'
      preLoaderRoute: typeof UseCasesRightsAndObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help/': {
      id: '/admin/help/'
      path: '/help'
      fullPath: '/admin/help/'
      preLoaderRoute: typeof AdminHelpIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help/$id': {
      id: '/admin/help/$id'
      path: '/help/$id'
      fullPath: '/admin/help/$id'
      preLoaderRoute: typeof AdminHelpIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help/new': {
      id: '/admin/help/new'
      path: '/help/new'
      fullPath: '/admin/help/new'
      preLoaderRoute: typeof AdminHelpNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/resources/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources/new': {
      id: '/admin/resources/new'
      path: '/resources/new'
      fullPath: '/admin/resources/new'
      preLoaderRoute: typeof AdminResourcesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/forms': {
      id: '/admin/settings/forms'
      path: '/settings/forms'
      fullPath: '/admin/settings/forms'
      preLoaderRoute: typeof AdminSettingsFormsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/settings/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/integrations': {
      id: '/admin/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/seo': {
      id: '/admin/settings/seo'
      path: '/settings/seo'
      fullPath: '/admin/settings/seo'
      preLoaderRoute: typeof AdminSettingsSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/team': {
      id: '/admin/settings/team'
      path: '/settings/team'
      fullPath: '/admin/settings/team'
      preLoaderRoute: typeof AdminSettingsTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stories/': {
      id: '/admin/stories/'
      path: '/stories'
      fullPath: '/admin/stories/'
      preLoaderRoute: typeof AdminStoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stories/$id': {
      id: '/admin/stories/$id'
      path: '/stories/$id'
      fullPath: '/admin/stories/$id'
      preLoaderRoute: typeof AdminStoriesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stories/new': {
      id: '/admin/stories/new'
      path: '/stories/new'
      fullPath: '/admin/stories/new'
      preLoaderRoute: typeof AdminStoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/help-centre/$category/$slug': {
      id: '/help-centre/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/help-centre/$category/$slug'
      preLoaderRoute: typeof HelpCentreCategorySlugRouteImport
      parentRoute: typeof HelpCentreRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminHelpIdRoute: typeof AdminHelpIdRoute
  AdminHelpNewRoute: typeof AdminHelpNewRoute
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminResourcesNewRoute: typeof AdminResourcesNewRoute
  AdminSettingsFormsRoute: typeof AdminSettingsFormsRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsIntegrationsRoute: typeof AdminSettingsIntegrationsRoute
  AdminSettingsSeoRoute: typeof AdminSettingsSeoRoute
  AdminSettingsTeamRoute: typeof AdminSettingsTeamRoute
  AdminStoriesIdRoute: typeof AdminStoriesIdRoute
  AdminStoriesNewRoute: typeof AdminStoriesNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminHelpIndexRoute: typeof AdminHelpIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminStoriesIndexRoute: typeof AdminStoriesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminHelpIdRoute: AdminHelpIdRoute,
  AdminHelpNewRoute: AdminHelpNewRoute,
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminResourcesNewRoute: AdminResourcesNewRoute,
  AdminSettingsFormsRoute: AdminSettingsFormsRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsIntegrationsRoute: AdminSettingsIntegrationsRoute,
  AdminSettingsSeoRoute: AdminSettingsSeoRoute,
  AdminSettingsTeamRoute: AdminSettingsTeamRoute,
  AdminStoriesIdRoute: AdminStoriesIdRoute,
  AdminStoriesNewRoute: AdminStoriesNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminHelpIndexRoute: AdminHelpIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminStoriesIndexRoute: AdminStoriesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CustomerStoriesRouteChildren {
  CustomerStoriesSlugRoute: typeof CustomerStoriesSlugRoute
  CustomerStoriesIndexRoute: typeof CustomerStoriesIndexRoute
}

const CustomerStoriesRouteChildren: CustomerStoriesRouteChildren = {
  CustomerStoriesSlugRoute: CustomerStoriesSlugRoute,
  CustomerStoriesIndexRoute: CustomerStoriesIndexRoute,
}

const CustomerStoriesRouteWithChildren = CustomerStoriesRoute._addFileChildren(
  CustomerStoriesRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface HelpCentreRouteChildren {
  HelpCentreIndexRoute: typeof HelpCentreIndexRoute
  HelpCentreCategorySlugRoute: typeof HelpCentreCategorySlugRoute
}

const HelpCentreRouteChildren: HelpCentreRouteChildren = {
  HelpCentreIndexRoute: HelpCentreIndexRoute,
  HelpCentreCategorySlugRoute: HelpCentreCategorySlugRoute,
}

const HelpCentreRouteWithChildren = HelpCentreRoute._addFileChildren(
  HelpCentreRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  R2Route: R2Route,
  AssetIntelligenceHubRoute: AssetIntelligenceHubRoute,
  BlogRoute: BlogRouteWithChildren,
  BookADemoRoute: BookADemoRoute,
  CustomerStoriesRoute: CustomerStoriesRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  HelpCentreRoute: HelpCentreRouteWithChildren,
  PlatformRoute: PlatformRoute,
  PortfolioIntelligenceRoute: PortfolioIntelligenceRoute,
  RequestADemoRoute: RequestADemoRoute,
  SecurityRoute: SecurityRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyCareersRoute: CompanyCareersRoute,
  CompanyContactRoute: CompanyContactRoute,
  CompanyPartnersRoute: CompanyPartnersRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalServiceLevelTermsRoute: LegalServiceLevelTermsRoute,
  LegalTermsRoute: LegalTermsRoute,
  SolutionsAcquisitionsDueDiligenceRoute:
    SolutionsAcquisitionsDueDiligenceRoute,
  SolutionsAssetManagersRoute: SolutionsAssetManagersRoute,
  SolutionsBuildingSurveyorsRoute: SolutionsBuildingSurveyorsRoute,
  SolutionsInvestmentManagersRoute: SolutionsInvestmentManagersRoute,
  SolutionsLegalsRoute: SolutionsLegalsRoute,
  SolutionsPropertyManagersRoute: SolutionsPropertyManagersRoute,
  UseCasesAssetDocumentReviewRoute: UseCasesAssetDocumentReviewRoute,
  UseCasesCriticalDatesRoute: UseCasesCriticalDatesRoute,
  UseCasesDilapidationsRoute: UseCasesDilapidationsRoute,
  UseCasesDueDiligenceRoute: UseCasesDueDiligenceRoute,
  UseCasesLeaseIntelligenceRoute: UseCasesLeaseIntelligenceRoute,
  UseCasesRightsAndObligationsRoute: UseCasesRightsAndObligationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
